FROM arm32v7/golang:alpine as build

WORKDIR /app

COPY go.mod .

RUN go mod download

COPY . .

RUN go build -o main .

FROM arm32v7/golang:alpine

COPY --from=build /app .

EXPOSE 8080

CMD [ "./main" ]
