apiVersion: v1
kind: Pod
metadata:
  name: gosay
  labels:
    app: gosay
spec:
  containers:
  - name: gosay
    image: localhost:5000/gosay
    resources:
      limits:
        memory: "50Mi"
        cpu: "250m"
    ports:
      - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: gosay-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: gosay
