apiVersion: v1
kind: Pod
metadata:
  name: gosay
  labels:
    app: gosay
spec:
  containers:
  - name: gosay
    image: localhost:5000/gosay
    resources:
      limits:
        memory: "50Mi"
        cpu: "250m"
    ports:
      - containerPort: 8080
