apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-strodrig
  namespace: cert-manager
spec:
  acme:
    email: steprodriguez10@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-strodrig-secret-key
    solvers:
    - selector:
        dnsZones:
          - "gosay.strodrig.dev"
          - "k3s.strodrig.dev"
      dns01:
        route53:
          region: eu-west-1
          accessKeyID: AKIATM4VH23IO7PUWVXW
          secretAccessKeySecretRef:
            name: acme-route53-strodrig-dev
            key: secret_key
