apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosay-deployment
  namespace: gosay
spec:
  selector:
    matchLabels:
      app: gosay
  template:
    metadata:
      labels:
        app: gosay
    spec:
      containers:
      - name: gosay
        image: localhost:5000/gosay
        resources:
          limits:
            memory: "3Mi"
            cpu: "1m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: gosay-service
  namespace: gosay
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: gosay

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gosay-ingress
  namespace: gosay
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-strodrig
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: gosay-service
          servicePort: 8080
  tls: # < placing a host in the TLS config will indicate a certificate should be created
  - hosts:
    - gosay.strodrig.dev
    secretName: gosay-strodrig-tls # < cert-manager will store the created certificate in this secret.
